version: "3"
services:
  eye:
    image: eyedected:v2
    restart : always
    container_name: eye-dected
    volumes:
      - ./settings.py:/root/web/eyedetected/settings.py 
    command: python3 manage.py runserver
    ports:
      - "8000:8000"
    tty: true 
