bind = '0.0.0.0:9002' #绑定ip和端口号 
timeout = 30 #超时 
workers = 1
threads = 4  #指定每个进程开启的线程数 
loglevel = 'info' #日志级别，这个日志级别指的是错误日志的级别，而访问日志的级别无法设置 
access_log_format = '%(t)s %(p)s %(h)s "%(r)s" %(s)s %(L)s %(b)s %(f)s" "%(a)s"' 
accesslog = "./fire_access.log" #访问日志文件 
errorlog = "./fire_error.log" #错误日志文件
reload = True
